/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';
import {
  Perspective,
} from './types';


export namespace Components {

  interface C1Workpad {
    'documentId': string;
  }
  interface C1WorkpadAttributes extends StencilHTMLAttributes {
    'documentId'?: string;
  }

  interface CoEditor {}
  interface CoEditorAttributes extends StencilHTMLAttributes {}

  interface CoLogin {}
  interface CoLoginAttributes extends StencilHTMLAttributes {}

  interface CoWorkspace {}
  interface CoWorkspaceAttributes extends StencilHTMLAttributes {}

  interface TextBlock {
    'id': string;
    'text': string;
  }
  interface TextBlockAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'onContent-changed'?: (event: CustomEvent) => void;
    'text'?: string;
  }

  interface TextNode {
    'createCommit': () => Promise<any[]>;
    'createPerspective': (serviceProvider: string, name: string) => Promise<void>;
    'defaultService': string;
    'isRootNode': boolean;
    'perspectiveId': string;
  }
  interface TextNodeAttributes extends StencilHTMLAttributes {
    'defaultService'?: string;
    'isRootNode'?: boolean;
    'onCreateSibling'?: (event: CustomEvent) => void;
    'perspectiveId'?: string;
  }

  interface UprtclToolbar {
    'defaultService': string;
    'perspective': Perspective;
  }
  interface UprtclToolbarAttributes extends StencilHTMLAttributes {
    'defaultService'?: string;
    'onCreateCommit'?: (event: CustomEvent<void>) => void;
    'onCreatePerspective'?: (event: CustomEvent<{
      name: string;
      serviceProvider: string;
    }>) => void;
    'onSelectPerspective'?: (event: CustomEvent<string>) => void;
    'perspective'?: Perspective;
  }
}

declare global {
  interface StencilElementInterfaces {
    'C1Workpad': Components.C1Workpad;
    'CoEditor': Components.CoEditor;
    'CoLogin': Components.CoLogin;
    'CoWorkspace': Components.CoWorkspace;
    'TextBlock': Components.TextBlock;
    'TextNode': Components.TextNode;
    'UprtclToolbar': Components.UprtclToolbar;
  }

  interface StencilIntrinsicElements {
    'c1-workpad': Components.C1WorkpadAttributes;
    'co-editor': Components.CoEditorAttributes;
    'co-login': Components.CoLoginAttributes;
    'co-workspace': Components.CoWorkspaceAttributes;
    'text-block': Components.TextBlockAttributes;
    'text-node': Components.TextNodeAttributes;
    'uprtcl-toolbar': Components.UprtclToolbarAttributes;
  }


  interface HTMLC1WorkpadElement extends Components.C1Workpad, HTMLStencilElement {}
  var HTMLC1WorkpadElement: {
    prototype: HTMLC1WorkpadElement;
    new (): HTMLC1WorkpadElement;
  };

  interface HTMLCoEditorElement extends Components.CoEditor, HTMLStencilElement {}
  var HTMLCoEditorElement: {
    prototype: HTMLCoEditorElement;
    new (): HTMLCoEditorElement;
  };

  interface HTMLCoLoginElement extends Components.CoLogin, HTMLStencilElement {}
  var HTMLCoLoginElement: {
    prototype: HTMLCoLoginElement;
    new (): HTMLCoLoginElement;
  };

  interface HTMLCoWorkspaceElement extends Components.CoWorkspace, HTMLStencilElement {}
  var HTMLCoWorkspaceElement: {
    prototype: HTMLCoWorkspaceElement;
    new (): HTMLCoWorkspaceElement;
  };

  interface HTMLTextBlockElement extends Components.TextBlock, HTMLStencilElement {}
  var HTMLTextBlockElement: {
    prototype: HTMLTextBlockElement;
    new (): HTMLTextBlockElement;
  };

  interface HTMLTextNodeElement extends Components.TextNode, HTMLStencilElement {}
  var HTMLTextNodeElement: {
    prototype: HTMLTextNodeElement;
    new (): HTMLTextNodeElement;
  };

  interface HTMLUprtclToolbarElement extends Components.UprtclToolbar, HTMLStencilElement {}
  var HTMLUprtclToolbarElement: {
    prototype: HTMLUprtclToolbarElement;
    new (): HTMLUprtclToolbarElement;
  };

  interface HTMLElementTagNameMap {
    'c1-workpad': HTMLC1WorkpadElement
    'co-editor': HTMLCoEditorElement
    'co-login': HTMLCoLoginElement
    'co-workspace': HTMLCoWorkspaceElement
    'text-block': HTMLTextBlockElement
    'text-node': HTMLTextNodeElement
    'uprtcl-toolbar': HTMLUprtclToolbarElement
  }

  interface ElementTagNameMap {
    'c1-workpad': HTMLC1WorkpadElement;
    'co-editor': HTMLCoEditorElement;
    'co-login': HTMLCoLoginElement;
    'co-workspace': HTMLCoWorkspaceElement;
    'text-block': HTMLTextBlockElement;
    'text-node': HTMLTextNodeElement;
    'uprtcl-toolbar': HTMLUprtclToolbarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
